/* 地图：每个去处的描述、出口和功能开关。加新场景改这里。 */

const MAP = {
  cunkou:{name:'杏花村·村口', desc:'村口一株老杏树，落英铺了满地。几个孩童追着黄狗跑过，远处炊烟袅袅。',
    exits:['kezhan','tiejiang','zhulin'],
    paodian:{act:'替村人挑水劈柴', exp:0.7, lv:1, tip:'虽是杂役，却也练力气'} },
  kezhan:{name:'杏花村·悦来客栈', desc:'店里飘着酒气和牛肉香。小二肩上搭着白布，正吆喝着上菜。这是新到江湖的人歇脚闲谈之处。',
    exits:['cunkou'], shop:'inn', treat:true, board:true, quest:true,
    paodian:{act:'在客栈打杂听闲话', exp:1.2, lv:1, tip:'江湖消息，都在酒桌上'} },
  tiejiang:{name:'杏花村·铁匠铺', desc:'炉火烧得通红，老铁匠光着膀子抡锤，火星子溅了一地。',
    exits:['cunkou'], shop:'smith', forge:true },
  zhulin:{name:'村外·竹林小径', desc:'竹影森森，风过处沙沙作响。林中常有剪径的毛贼出没，也常见有人在此盘膝打坐。',
    exits:['cunkou','shanlu'], hunt:['pi','lang','zei'],
    paodian:{act:'竹下盘膝打坐', exp:2.2, lv:5, tip:'心静则气自生'} },
  shanlu:{name:'后山·瀑布', desc:'一道白练从崖顶垂下，水声轰鸣。崖壁上依稀刻着几行剑痕。',
    exits:['zhulin','guandao'], hunt:['xiong','zeitou'],
    paodian:{act:'立于瀑下练功', exp:5, lv:15, tip:'以水磨骨，事半功倍'} },
  guandao:{name:'洛阳·官道', desc:'黄土大道上车马不绝。道旁茶棚里，几个挎刀的汉子正打量着过路人。',
    exits:['shanlu','chengnei','xueshan'], hunt:['mazei','ebar'] },
  xueshan:{name:'塞北·风雪谷', desc:'出关往北，风雪扑面，人马难行。谷中狼嚎彻夜不绝，据说也有中原过不下去的人躲在这里。',
    exits:['guandao','jueding'], hunt:['xuelang','cike'],
    paodian:{act:'踏雪立桩', exp:12, lv:45, tip:'苦寒之地，最磨心志'} },
  jueding:{name:'西域·星宿海', desc:'瀚海尽头，星子低得像要压到头顶。传说魔教总坛就在这一带，寻常人有来无回。',
    exits:['xueshan'], hunt:['hufa','laoguai'],
    paodian:{act:'观星吐纳', exp:18, lv:60, tip:'天地灵气，此处最盛'} },
  chengnei:{name:'洛阳城·长街', desc:'满城牡丹，人声鼎沸。街口贴着武林大会的告示，围了一圈人。',
    exits:['guandao','leitai','shanmen','duchang'], shop:'city', market:true, forge:true, board:true },
  leitai:{name:'洛阳城·比武擂台', desc:'高台三丈，四角挑着红绸。台下人山人海，喝彩声一浪高过一浪。此处可与人较技，也可挑战守擂高手。',
    exits:['chengnei'], arena:true, pk:true },
  duchang:{name:'洛阳城·地下赌坊', desc:'烟雾缭绕，骰盅碰得叮当响。庄家眯着眼，笑得像只老狐狸。',
    exits:['chengnei'], gamble:true },
  shanmen:{name:'山门前', desc:'青石阶蜿蜒而上，云雾深处隐约可见殿宇飞檐。这里是各大门派收徒之地。',
    exits:['chengnei','sect'], joinsect:true },
  sect:{name:'本门·后山', desc:'松风阵阵，同门弟子的吆喝声隐隐传来。师父就在前面的石台上打坐。',
    exits:['shanmen'], learn:true, gang:true, sectOnly:true,
    paodian:{act:'面壁参悟本门心法', exp:11, lv:30, tip:'门派重地，灵气充盈'} },
};

/*#node*/ module.exports = { MAP };
